### PR TITLE
[EOSF-441] Revise small things per Nici's suggestions

### PR DESCRIPTION
**Pull request by hmoco**
## Purpose
 - Revise landing page placeholder data
 - remove hard-coded providers
 - use new EGAP logo
 - update to latest Ember-osf for current copyright footer info
 - Do not allow registration type selection unless OSF is the only provider selected

## Changes
screen shot 2017-02-21 at 1 42 30 pm
screen shot 2017-02-21 at 1 42 24 pm
screen shot 2017-02-21 at 1 42 09 pm

### CODE REVIEW

**Comment by hmoco** [comment]
@brianjgeiger, travis seems to be having trouble loading ember-osf from the npm registry. Tests pass locally, however.

**Comment by brianjgeiger** [comment]
@hmoco Is everything set right with the yarn lockfile?

**Comment by hmoco** [comment]
Canceled build to try with pinned ember-osf version

**Review by brianjgeiger — CHANGES_REQUESTED** [review]
:tada::penguin::tada:

**Review by brianjgeiger — APPROVED** [review]

**Pull request merged**
