### PR TITLE
[EOSF-460] Pinning specific versions of most packages. So far no errors

### PR DESCRIPTION
**Pull request by hmoco**
## Ticket
https://openscience.atlassian.net/browse/EOSF-460

## Purpose 
Pin to specific versions of dependencies when possible

### CODE REVIEW

**Comment by hmoco** [comment]
Removed the `^` and `~` dependency versions and kept them at the state they were, besides the ones that were making tests fail at that version, which were then updated to the latest version of that package.

**Comment by binoculars** [comment]
I prefer pinned versions and explicitly upgrading them. A lot of maintainers don't follow semver, so this is definitely an improvement. We can use tools like greenkeeper to PR the repo automatically for updates.

**Comment by hmoco** [comment]
@binoculars, sweet! So is this good for code review? And should the same be done for ember-preprints?

**Review by binoculars — APPROVED** [review]
👍

**Comment by binoculars** [comment]
Go for it in preprints! I did the same thing mostly in CenterForOpenScience/ember-osf#191, but probably should just remove all of the carets and tildes in the packages that I didn't touch.

**Pull request merged**
